apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector-sa
  namespace: opentelemetry-operator-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::__AWS_ACCOUNT_ID__:role/robot-telemetry-full-20260824-adot-collector-irsa
